name: cf_workers
description: Cloudflare Workers Dart
version: 2025.5.15
repository: https://github.com/a-skua/cf_workers.dart

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.4.0
  poor_web: ^2025.5.15+1
  web: ^1.1.1

dev_dependencies:
  test: ^1.24.0
  lints: ^5.1.1
